### ISSUE TITLE
Making arguments private

### ISSUE THREAD

**Issue by amerritt14** [carlzulauf/opt_struct#4]
I find that I don't always want to expose the arguments, but I do want to require them.
```ruby
class Uppercase < OptStruct.new
  required :my_string
  def perform
    string.upcase
  end
end
```
I don't necessarily want to access `:my_string` from outside the object, but I do want to require it.
```ruby
upcase_string = Uppercase.new(my_string: "check it out").perform
```

### Suggestion:

Add a "private" flag to options.
```ruby
class Uppercase < OptStruct.new
  required :my_string, private: true
  # Or: option :my_string, required: true, private: true
  def perform
    string.upcase
  end
end
```

### Implementation
This is my idea for implementation. I'm happy to play with this and submit a PR if you think it's worth adding.
```ruby
# class_methods.rb
def option(key, default = nil, **options)
  default = options[:default] if options.key?(:default)
  defaults[key] = default
  required_keys << key if options[:required]
  option_accessor key
  # Make the accessors private
  private key if options[:private]
end
```

**Comment by carlzulauf** [comment]
I like this suggestion. Seems like this could be integrated in a way that feels natural. Not sure yet if there are edge cases I haven't considered. Feel free to take a stab at this. I will wait a while for a PR and if I don't see one might try making this change myself.
